config:
  #爬虫状态
  debug: true
  #项目名称
  botname : spiderCompany
  # 下载器并发数量
  concurrentRequest : 1
  # 请求延迟，单位 s
  concurrentRequestSleep : 6
  # 持久化并发数量
  concurrentPipeline : 0
  # 持久化延迟，单位s
  concurrentPipelineSleep : 5
  #代理池key
  proxyKey : MemoryProxyPool
  #cookie池key
  cookieKey : MemoryCookiePool
  #UserAgent池key
  userAgentKey : MemoryUserAgentPool
  #log存放目录
  logPath : /data/logs/example/
  #下载器解析的队列配置，要和队列名称保持一致
  keys : [a,b,c,d]


redis:
  host : 127.0.0.1
  port : 6379
  password : mypass
  db : 0

mongo:
  host : 127.0.0.1
  port : 27017
  db : mydb